export const INITIAL_CRYPTO = [
    { symbol: "BINANCE:BTCUSDT", description: "Bitcoin / Tether" },
    { symbol: "BINANCE:ETHUSDT", description: "Ethereum / Tether" },
    { symbol: "BINANCE:SOLUSDT", description: "Solana / Tether" },
    { symbol: "BINANCE:BNBUSDT", description: "Binance Coin / Tether" },
    { symbol: "BINANCE:XRPUSDT", description: "XRP / Tether" },
    { symbol: "BINANCE:ADAUSDT", description: "Cardano / Tether" },
    { symbol: "BINANCE:DOGEUSDT", description: "Dogecoin / Tether" },
    { symbol: "BINANCE:AVAXUSDT", description: "Avalanche / Tether" },
    { symbol: "BINANCE:DOTUSDT", description: "Polkadot / Tether" },
    { symbol: "BINANCE:MATICUSDT", description: "Polygon / Tether" },
    { symbol: "BINANCE:LINKUSDT", description: "Chainlink / Tether" },
    { symbol: "BINANCE:LTCUSDT", description: "Litecoin / Tether" },
    { symbol: "BINANCE:UNIUSDT", description: "Uniswap / Tether" },
    { symbol: "BINANCE:ATOMUSDT", description: "Cosmos / Tether" },
    { symbol: "BINANCE:NEARUSDT", description: "Near / Tether" },
    { symbol: "BINANCE:ARBUSDT", description: "Arbitrum / Tether" },
    { symbol: "BINANCE:OPUSDT", description: "Optimism / Tether" },
    { symbol: "BINANCE:APTUSDT", description: "Aptos / Tether" },
    { symbol: "BINANCE:PEPEUSDT", description: "Pepe / Tether" },
    { symbol: "BINANCE:SHIBUSDT", description: "Shiba Inu / Tether" },
];
